'use strict';

/**
 * Demo data seeder - realistic Philippine fleet data.
 *
 * Runs automatically on first boot when the drivers table is empty, and can be
 * run manually with `node seed.js` against an existing database. Uses a fixed
 * PRNG seed so the generated fleet is identical on every machine, which keeps
 * screenshots and the year-end report reproducible.
 */

const fs = require('node:fs');
const path = require('node:path');
const initSqlJs = require('sql.js');

// Mulberry32 - small deterministic PRNG.
function makeRandom(seed) {
  let a = seed >>> 0;
  return function random() {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const FLEET = [
  { name: 'Rodrigo "Rudy" Alvarez', vehicle: 'Mitsubishi Canter FE', plate: 'NCR 8452', fuelType: 'diesel', rate: 9.4, price: 68.75 },
  { name: 'Maria L. Santos', vehicle: 'Isuzu Elf 4WD2', plate: 'NCR 1907', fuelType: 'diesel', rate: 8.1, price: 68.20 },
  { name: 'Jayson P. Villanueva', vehicle: 'Toyota Hilux 2.8 SRV', plate: 'NCR 6231', fuelType: 'diesel', rate: 11.2, price: 69.10 },
  { name: 'Analyn C. dela Cruz', vehicle: 'Nissan Urvan NV350', plate: 'NCR 3318', fuelType: 'diesel', rate: 7.6, price: 67.95 },
  { name: 'Ernesto B. Aquino', vehicle: 'Ford Ranger Wildtrak', plate: 'NCR 7742', fuelType: 'diesel', rate: 10.3, price: 68.60 },
  { name: 'Kristine M. Ramos', vehicle: 'Toyota Fortuner 2.8', plate: 'NCR 5106', fuelType: 'diesel', rate: 9.8, price: 69.35 },
  { name: 'Danilo S. Mercado', vehicle: 'Hyundai Accent 1.6', plate: 'NCR 2288', fuelType: 'petrol', rate: 13.7, price: 74.85 },
  { name: 'Michael O. Reyes', vehicle: 'Isuzu D-Max 3.0', plate: 'NCR 9044', fuelType: 'diesel', rate: 10.9, price: 69.00 },
  { name: 'Carmela T. Fernandez', vehicle: 'Toyota Innova 2.0', plate: 'NCR 6613', fuelType: 'petrol', rate: 12.4, price: 74.20 },
  { name: 'Rafael N. Domingo', vehicle: 'Mitsubishi L300 FB', plate: 'NCR 4075', fuelType: 'diesel', rate: 12.8, price: 68.40 },
];

const USERS = [
  { username: 'manager', role: 'manager' },
  { username: 'viewer', role: 'viewer' },
];

const PASSWORD = 'demo1234';

function hashPassword(password) {
  const crypto = require('node:crypto');
  const salt = crypto.randomBytes(16);
  const derived = crypto.scryptSync(String(password), salt, 64);
  return `scrypt$${salt.toString('hex')}$${derived.toString('hex')}`;
}

/**
 * Builds a year's worth of fuel entries per driver.
 *
 * Odometer readings are generated by advancing a plausible distance between
 * fills, so the consumption maths in /api/stats produces a real km/L figure
 * rather than echoing the configured rate back.
 */
function seedDemoData(db, q) {
  const random = makeRandom(20260406);
  const now = new Date();
  const currentYear = now.getFullYear();

  // Fifteen months of history so the year-over-year report has a real baseline.
  const start = new Date(Date.UTC(currentYear - 1, 2, 1));
  const today = new Date(Date.UTC(currentYear, now.getMonth(), now.getDate()));

  const createdAt = new Date().toISOString();
  const driverIds = [];

  FLEET.forEach((d) => {
    db.run(
      'INSERT INTO drivers (name, vehicle, plate, fuelType, consumptionRate, defaultPrice, createdAt) VALUES (?, ?, ?, ?, ?, ?, ?)',
      [d.name, d.vehicle, d.plate, d.fuelType, d.rate, d.price, createdAt]
    );
    driverIds.push(Number(db.exec('SELECT last_insert_rowid() AS id')[0].values[0][0]));
  });

  // One driver-facing account per driver, plus manager/viewer.
  driverIds.forEach((id, i) => {
    const handle = `driver${i + 1}`;
    db.run('INSERT INTO users (username, password, role, driverId) VALUES (?, ?, ?, ?)', [
      handle, hashPassword(PASSWORD), 'driver', id,
    ]);
  });
  USERS.forEach((u) => {
    db.run('INSERT INTO users (username, password, role, driverId) VALUES (?, ?, ?, ?)', [
      u.username, hashPassword(PASSWORD), u.role, null,
    ]);
  });

  let recordCount = 0;

  FLEET.forEach((fleet, index) => {
    const driverId = driverIds[index];
    let odometer = Math.floor(40000 + random() * 90000);
    // Each vehicle has its own real-world efficiency, slightly off its nominal
    // rate: idling in Manila traffic, load, and tyre condition all matter.
    const realEfficiency = fleet.rate * (0.88 + random() * 0.22);

    let cursor = new Date(start);
    // Stagger each driver so entries do not all land on the same day.
    cursor.setUTCDate(cursor.getUTCDate() + Math.floor(random() * 20));

    while (cursor <= today) {
      // Distance between fills: aim to empty most of the tank each time.
      const targetKm = realEfficiency * (38 + random() * 22);
      odometer += Math.round(targetKm);
      const liters = Math.round((targetKm / realEfficiency) * (0.96 + random() * 0.08) * 100) / 100;

      // Fuel price drifts over time, and wobbles week to week.
      const yearFraction = (cursor.getUTCFullYear() - start.getUTCFullYear()) +
        (cursor.getUTCMonth() - start.getUTCMonth()) / 12;
      const drift = 1 - 0.06 * yearFraction;
      const wobble = 0.97 + random() * 0.07;
      const price = Math.round(fleet.price * drift * wobble * 100) / 100;
      const total = Math.round(liters * price * 100) / 100;

      const dateStr = cursor.toISOString().slice(0, 10);
      db.run(
        'INSERT INTO records (driverId, date, liters, pricePerLiter, total, odometer, createdAt) VALUES (?, ?, ?, ?, ?, ?, ?)',
        [driverId, dateStr, liters, price, total, odometer, createdAt]
      );
      recordCount += 1;

      // Two to four weeks to the next fill.
      cursor = new Date(cursor.getTime() + (12 + Math.floor(random() * 14)) * 24 * 3600 * 1000);
    }
  });

  return { drivers: FLEET.length, records: recordCount, users: FLEET.length + USERS.length };
}

module.exports = { seedDemoData, PASSWORD };

// Standalone: node seed.js  -> seeds DB_PATH directly.
if (require.main === module) {
  const DB_PATH = process.env.DB_PATH || path.join(__dirname, 'data', 'driverledger.db');
  (async () => {
    const SQL = await initSqlJs();
    let data = null;
    if (fs.existsSync(DB_PATH)) data = new Uint8Array(fs.readFileSync(DB_PATH));
    const db = new SQL.Database(data || undefined);
    const existing = db.exec('SELECT COUNT(*) AS n FROM drivers');
    if (existing[0] && existing[0].values[0][0] > 0) {
      console.log('Database already has drivers - nothing seeded. Delete the file to reseed.');
      process.exit(0);
    }
    db.run(`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'viewer', driverId INTEGER)`);
    db.run(`CREATE TABLE IF NOT EXISTS drivers (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, vehicle TEXT NOT NULL, plate TEXT UNIQUE, fuelType TEXT DEFAULT 'diesel', consumptionRate REAL DEFAULT 0, defaultPrice REAL DEFAULT 60, createdAt TEXT)`);
    db.run(`CREATE TABLE IF NOT EXISTS records (id INTEGER PRIMARY KEY AUTOINCREMENT, driverId INTEGER NOT NULL, date TEXT NOT NULL, liters REAL NOT NULL, pricePerLiter REAL NOT NULL, total REAL NOT NULL, odometer REAL DEFAULT 0, createdAt TEXT)`);
    const counts = seedDemoData(db);
    const dir = path.dirname(DB_PATH);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(DB_PATH, Buffer.from(db.export()));
    console.log(`Seeded ${counts.drivers} drivers, ${counts.records} records, ${counts.users} users into ${DB_PATH}`);
  })();
}
